import Image from 'next/image';
import content from './content.json';
import {Locale,Page,pages,labels,href,tr} from './i18n';
import Preferences from './Preferences';
import Lab from './Lab';
import Atlas from './Atlas';
import Health from './Health';

const repo='https://github.com/BAT-El34/arccraft-research-companion';
function Provenance({locale}:{locale:Locale}){return <details className="provenance"><summary>{tr(locale,'Evidence & version','Preuve et version')} ↗</summary><p>{tr(locale,'Candidate · locally reproduced · final archive pending.','Version candidate · reproduite localement · archive finale en attente.')}</p><dl><dt>{tr(locale,'Scientific commit','Commit scientifique')}</dt><dd><a href={`${repo}/tree/${content.manifest.source_commit}`}><code>{content.manifest.source_commit}</code></a></dd><dt>{tr(locale,'Engine / grammar','Moteur / grammaire')}</dt><dd>{content.manifest.engine_declared_version} / {content.manifest.world_grammar_version}</dd><dt>{tr(locale,'Registry','Registre')}</dt><dd><a href="/data/registry.json">JSON · SHA-256 · sources</a></dd></dl></details>}
function Notice({locale}:{locale:Locale}){return <aside className="notice"><span className="notice-mark">!</span><p><strong>{tr(locale,'Preliminary evaluation. Partial external validation.','Évaluation préliminaire. Validation externe partielle.')}</strong><br/>{tr(locale,'Exact replay is computational evidence. It does not establish predictive superiority or real-world causal attribution.','Un replay exact constitue une preuve informatique. Il ne démontre ni supériorité prédictive ni attribution causale réelle.')}</p></aside>}
const limits=[
  ['Predictive calibration','No incurred outcome is covered by the reported process intervals. The final evaluation year has already been inspected.','Calibration prédictive','Aucun coût observé n’est couvert par les intervalles de processus rapportés. La dernière année d’évaluation a déjà été examinée.'],
  ['Uncertainty','Process intervals omit parameter and model uncertainty. A small point error is not a calibration test.','Incertitude','Les intervalles de processus omettent l’incertitude des paramètres et du modèle. Une faible erreur ponctuelle ne teste pas la calibration.'],
  ['Synthetic plausibility','World classes, probabilities, dependencies and transition rules are assumptions, not an empirical calibration of the motor portfolio.','Plausibilité synthétique','Les classes, probabilités, dépendances et transitions sont des hypothèses, pas une calibration empirique du portefeuille automobile.'],
  ['Failure attribution','The atlas identifies coded gates. It provides neither causal labels nor validated diagnostic accuracy.','Attribution des échecs','L’Atlas identifie les seuils codés. Il n’apporte ni étiquette causale ni précision diagnostique validée.'],
  ['Severity and expenses','Policy-year incurred amounts are not individual claim severities. Expenses and commissions are unavailable unless supplied as exploratory assumptions.','Sévérité et frais','Les coûts par police-année ne sont pas des sévérités de sinistres individuels. Frais et commissions restent indisponibles sans hypothèses exploratoires explicites.'],
  ['External validity','The Spanish portfolio cannot establish transfer to Togo, Mixx by Yas or the CIMA market. Independent data and untouched forecast periods are needed.','Validité externe','Le portefeuille espagnol ne démontre pas de transférabilité au Togo, à Mixx by Yas ou au marché CIMA. Des données indépendantes et des périodes non examinées sont nécessaires.'],
  ['Runtime','Historical timings describe one host. They are not a promise of web response time or a general speed ranking.','Durée','Les mesures historiques décrivent un hôte. Elles ne promettent ni délai web ni classement général de performance.']
];

function Home({locale}:{locale:Locale}){return <>
  <section className="hero"><div><p className="eyebrow">ARCCRAFT / {tr(locale,'RESEARCH COMPANION','COMPAGNON SCIENTIFIQUE')}</p><h1>{tr(locale,'Stress the model.\nInspect the evidence.','Éprouver le modèle.\nExaminer les preuves.')}</h1><p className="hero-sub">{tr(locale,'A reproducible architecture for procedural stress testing of actuarial models.','Une architecture reproductible pour les tests de résistance procéduraux des modèles actuariels.')}</p><div className="actions"><a className="button primary" href={href(locale,'paper')}>{tr(locale,'Read the paper','Lire l’article')} ↗</a><a className="button" href={href(locale,'evidence')}>{tr(locale,'Inspect the evidence','Examiner les preuves')} →</a></div></div><div className="architecture" aria-label={tr(locale,'Procedural workflow','Chaîne procédurale')}><span className="eyebrow">{tr(locale,'FROM SPECIFICATION TO EVIDENCE','DE LA SPÉCIFICATION À LA PREUVE')}</span>{['SPECIFICATION','WORLDS / PCG64','PASS · REPAIR · REJECT','TRAJECTORIES','FAILURE ATLAS'].map((name,i)=><div className="arch-node" key={name}><span>0{i+1}</span>{name}{i<4&&<b aria-hidden="true">↓</b>}</div>)}<small>{tr(locale,'Replay ≠ empirical validation','Replay ≠ validation empirique')}</small></div></section>
  <Notice locale={locale}/><section className="section"><div className="section-heading"><h2>{tr(locale,'What the evidence supports','Ce que les preuves établissent')}</h2><a href={href(locale,'evidence')}>{tr(locale,'Open claim register','Ouvrir le registre')} ↗</a></div><div className="metrics">{[content.claims[2],content.claims[1],content.claims[6]].map(c=><article className="metric" key={c.claim_id}><span className="eyebrow">{c.claim_id} / {tr(locale,'REFERENCE RESULT','RÉSULTAT DE RÉFÉRENCE')}</span><h3>{locale==='fr'?c.claim_fr:c.claim}</h3><p className="metric-value">{c.observed_result.split(';')[0]}</p><p>{locale==='fr'?c.scope_fr:c.evidential_scope}</p><a href={`${href(locale,'evidence')}#${c.claim_id}`}>{tr(locale,'Definition, source & limits','Définition, source et limites')} →</a></article>)}</div></section>
  <section className="section paper-teaser"><p className="eyebrow">{tr(locale,'THE SCIENTIFIC PAPER','L’ARTICLE SCIENTIFIQUE')}</p><h2>{content.title}</h2><p>Elia Batako · Manuel Ntumba</p><p>{tr(locale,'Scientific draft · reviewed companion candidate · author affiliations and archive DOI pending.','Manuscrit scientifique · compagnon candidat revu · affiliations et DOI d’archive à compléter.')}</p><a href={href(locale,'paper')}>{tr(locale,'Abstract, methods and full manuscript','Résumé, méthodes et manuscrit intégral')} ↗</a></section>
  <section className="section"><h2>{tr(locale,'Three distinct ways to read a result','Trois façons distinctes de lire un résultat')}</h2><div className="cards">{[['paper','Reference','Référence','Frozen evidence from the inspected research. Candidate publication status remains explicit.','Preuves figées de la recherche auditée. Le statut de publication candidat reste explicite.'],['lab','Live replay','Replay en direct','Run the frozen computation and compare its fingerprint with the registered reference.','Exécuter le calcul figé et comparer son empreinte à la référence enregistrée.'],['lab','Exploration','Exploration','Change assumptions in a separate run. New outputs never replace the reference.','Modifier les hypothèses dans un run distinct. Les nouvelles sorties ne remplacent jamais la référence.']].map(([page,en,fr,body,bodyFr])=><a className="card" key={en} href={href(locale,page as Page)}><h3>{tr(locale,en,fr)} ↗</h3><p>{tr(locale,body,bodyFr)}</p></a>)}</div></section><Provenance locale={locale}/>
</>}

function Paper({locale}:{locale:Locale}){const pdf=content.registry.artifacts.find(a=>a.path==='publication/latex/main.pdf');return <>
  <p className="lead">{content.title}</p><p>Elia Batako · Manuel Ntumba</p><p>{tr(locale,'Affiliations, ORCID and corresponding author: pending author input. Target journal is not evidence of acceptance.','Affiliations, ORCID et correspondant : à compléter par les auteurs. La revue cible ne constitue pas une preuve d’acceptation.')}</p><div className="actions">{pdf&&<a className="button primary" href={pdf.url}>PDF ↗</a>}<a className="button" href="/downloads/publication/manuscript.md">{tr(locale,'Full manuscript · Markdown','Manuscrit intégral · Markdown')} ↓</a><a href="/citations/arccraft.bib">BibTeX ↓</a></div><Notice locale={locale}/>
  <article className="reading"><h2>Abstract <span className="eyebrow">EN / ORIGINAL</span></h2><p>{content.abstract}</p>{locale==='fr'&&<><h2>Résumé <span className="eyebrow">FR / TRADUCTION</span></h2><p>ARCCRAFT propose une architecture procédurale versionnée pour faire évoluer des mondes d’assurance synthétiques avec des états, transitions, bornes, flux aléatoires et critères d’échec explicites. L’évaluation distingue la vérification informatique de la prévision empirique. L’étude rétrospective automobile améliore la discrimination de fréquence par police, sans améliorer toutes les erreurs agrégées. Le modèle de coût est instable entre les années et ses intervalles ne couvrent pas les coûts observés. Les ablations synthétiques établissent un replay local exact et l’isolation des flux nommés. La plupart des échecs proviennent toutefois du seuil opérationnel de traçabilité. Les résultats soutiennent une architecture d’audit reproductible dans l’environnement inspecté, sans établir de plausibilité calibrée des scénarios, de supériorité prédictive générale, d’attribution causale ou de validité externe.</p></>}<p className="muted">{tr(locale,'Abstract values are authored statements linked to the claim register and complete source manuscript.','Les valeurs du résumé sont des énoncés du manuscrit reliés au registre des claims et à la source intégrale.')}</p><a href={href(locale,'evidence')}>{tr(locale,'Verify the numerical claims','Vérifier les claims numériques')} →</a><h2>{tr(locale,'Methods at a glance','Méthodes en bref')}</h2><p>{tr(locale,'The empirical benchmark compares aggregate and policy-level actuarial models using temporal evaluation. The synthetic experiment registers independent stochastic streams, validates states and applies noncompensatory gates to multi-period trajectories. Controlled ablations test validator policy, transitions and stream isolation.','Le benchmark empirique compare des modèles agrégés et par police avec une évaluation temporelle. L’expérience synthétique enregistre des flux aléatoires indépendants, valide les états et applique des seuils non compensatoires aux trajectoires. Des ablations contrôlées testent le validateur, les transitions et l’isolation des flux.')}</p><h2>{tr(locale,'Editorial reconciliation','Réconciliation éditoriale')}</h2><p>{tr(locale,'This companion incorporates the approved incurred-error, first-decile and raw-source corrections. Original research snapshots are preserved in the repository. The corrected manuscript and the historical artifact have distinct hashes.','Ce compagnon intègre les corrections validées de l’erreur de coût, du premier décile et de la source brute. Les originaux sont conservés dans le dépôt. Le manuscrit corrigé et l’artefact historique ont des empreintes distinctes.')}</p></article><Provenance locale={locale}/>
</>}

function Evidence({locale}:{locale:Locale}){return <><p className="lead">{tr(locale,'Every claim has a metric, a source and a boundary.','Chaque claim possède une métrique, une source et une limite.')}</p><Notice locale={locale}/><div className="claim-nav">{content.claims.map(c=><a href={`#${c.claim_id}`} key={c.claim_id}>{c.claim_id}</a>)}</div>{content.claims.map(c=><article className="claim" id={c.claim_id} key={c.claim_id}><div><span className="eyebrow">{c.claim_id} / {c.proof_status}</span><h2>{locale==='fr'?c.claim_fr:c.claim}</h2><p className="result">{c.observed_result}</p><p>{locale==='fr'?c.scope_fr:c.evidential_scope}</p></div><dl><dt>{tr(locale,'Metric','Métrique')}</dt><dd>{locale==='fr'?c.metric_fr:c.metric}</dd><dt>{tr(locale,'Formula / unit','Formule / unité')}</dt><dd>{c.formula} · {c.unit}</dd><dt>{tr(locale,'Population / period','Population / période')}</dt><dd>{c.population}</dd><dt>Source</dt><dd><a href={c.source_url}>{c.source_files} ↓</a></dd><dt>SHA-256</dt><dd><code>{c.source_sha256}</code></dd><dt>{tr(locale,'Verification commit','Commit de vérification')}</dt><dd><code>{c.verification_commit}</code></dd><dt>{tr(locale,'Version / publication','Version / publication')}</dt><dd>{c.version} / CANDIDATE</dd><dt>{tr(locale,'Historical producer','Producteur historique')}</dt><dd>{tr(locale,'Original producing commit unknown; local verification commit is recorded separately.','Commit producteur original inconnu ; le commit de vérification locale est enregistré séparément.')}</dd></dl><details><summary>{tr(locale,'Full-precision values','Valeurs à pleine précision')}</summary><pre>{JSON.stringify(c.recomputed,null,2)}</pre></details></article>)}</>}

function Figures({locale}:{locale:Locale}){return <><p className="lead">{tr(locale,'Read the figure. Inspect its data. Reproduce the result.','Lire la figure. Inspecter ses données. Reproduire le résultat.')}</p>{content.figures.map(f=><figure className="figure" id={`figure-${f.number}`} key={f.number}><div className="section-heading"><h2>{f.number.toString().padStart(2,'0')} / {locale==='fr'?f.title_fr:f.title}</h2><a href={f.image.url}>PNG ↓</a></div><div className="figure-image"><Image src={f.image.url} width={1400} height={900} alt={f.caption} style={{width:'100%',height:'auto'}}/></div><figcaption><span className="eyebrow">{tr(locale,'ORIGINAL ENGLISH CAPTION','LÉGENDE ORIGINALE EN ANGLAIS')}</span><p>{f.caption}</p></figcaption><div className="actions"><a href={f.script.url}>{tr(locale,'Reproduction script','Script de reproduction')} ↓</a>{f.sources.map(s=><a key={s.id} href={s.url}>{s.path.split('/').pop()} ↓</a>)}</div><details><summary>{tr(locale,'Figure provenance','Provenance de la figure')}</summary><p>{f.image.proof_status} · {f.image.version} · CANDIDATE</p><p><code>{f.image.sha256}</code></p><p>{tr(locale,'Scientific verification commit','Commit de vérification scientifique')} : <code>{f.image.science_commit}</code></p><p>{tr(locale,'Reuse licence awaits author decision.','Licence de réutilisation à préciser par les auteurs.')}</p></details></figure>)}</>}

function Data({locale}:{locale:Locale}){return <><p className="lead">{tr(locale,'A traceable public source. A bounded empirical use.','Une source publique traçable. Un usage empirique délimité.')}</p><article className="panel"><h2>Motor insurance portfolio</h2><p>Priscila Espinosa · Josep Lledó · David Atance</p><p><a href="https://data.mendeley.com/datasets/sw4jmdb2sm/1">Mendeley Data · 10.17632/sw4jmdb2sm.1 ↗</a></p><dl><dt>{tr(locale,'Licence / version','Licence / version')}</dt><dd>CC BY 4.0 / v1</dd><dt>SHA-256 · CSV</dt><dd><code>{content.data.sha256}</code></dd><dt>SHA-256 · {tr(locale,'dictionary','dictionnaire')}</dt><dd><code>{content.data.dictionary_sha256}</code></dd><dt>{tr(locale,'Checks','Contrôles')}</dt><dd>{Object.entries(content.data.checks).map(([key,value])=><div key={key}>{value?'✓':'✕'} {key}</div>)}</dd></dl><p>{tr(locale,'Local raw bytes match the recorded ingestion and ZIP. No fresh publisher download was performed. All normalized cells were compared with the research derivative. Source files were kept unchanged.','Les octets locaux correspondent au manifeste d’ingestion et au ZIP. Aucun nouveau téléchargement éditeur n’a été réalisé. Toutes les cellules normalisées ont été comparées au dérivé de recherche. Les sources sont intactes.')}</p><a href="/data/provenance.json">{tr(locale,'Schema, transformations & reconciliation · JSON','Schéma, transformations et réconciliation · JSON')} ↓</a></article><section className="section"><h2>{tr(locale,'From raw data to the published evidence','De la donnée brute aux preuves de l’article')}</h2><ol className="steps"><li>{tr(locale,'Publisher CSV + variable dictionary → recorded checksums.','CSV éditeur + dictionnaire → empreintes enregistrées.')}</li><li>{tr(locale,'Normalized research table → cell-level equality audit.','Table de recherche normalisée → audit d’égalité cellule par cellule.')}</li><li>{tr(locale,'Offline calibration and temporal benchmarks → versioned aggregate artifacts.','Calibration hors ligne et benchmarks temporels → artefacts agrégés versionnés.')}</li><li>{tr(locale,'Compact calibration → bounded replay; target outcomes used only for evaluation.','Calibration compacte → replay borné ; réalisations cibles utilisées uniquement pour l’évaluation.')}</li></ol><p>{tr(locale,'Raw policy data are not served by this application. WDI, HCI, Findex and other local datasets are excluded from the scientific results until independently qualified.','Les données individuelles brutes ne sont pas servies par cette application. WDI, HCI, Findex et les autres bases locales sont exclues des résultats avant qualification indépendante.')}</p></section><Provenance locale={locale}/></>}

function Reproducibility({locale}:{locale:Locale}){return <><p className="lead">{tr(locale,'The same inputs. An explicit environment. A comparable fingerprint.','Les mêmes entrées. Un environnement explicite. Une empreinte comparable.')}</p><Health locale={locale}/><div className="cards"><article className="panel"><h2>{tr(locale,'Frozen science','Science figée')}</h2><code>{content.manifest.source_commit}</code><p>{tr(locale,'Canonical output SHA-256','SHA-256 de la sortie canonique')}</p><code>{content.manifest.canonical_full_precision_semantic_sha256}</code><p>{tr(locale,'Full-precision compact sorted JSON; null for undefined metrics.','JSON compact trié à pleine précision ; null pour les métriques indéfinies.')}</p><p>{tr(locale,'The historical fingerprint uses a separate rounding contract.','L’empreinte historique utilise un contrat d’arrondi distinct.')}</p></article><article className="panel"><h2>{tr(locale,'Local replay','Replay local')}</h2><pre>python -m pip install numpy==2.3.5{'\n'}python scripts/replay_canonical.py{'\n'}python scripts/verify_checksums.py</pre><a href={`${repo}/tree/main/scripts`}>{tr(locale,'Scripts and instructions','Scripts et instructions')} ↗</a><p><a href="/downloads/requirements-replay.lock">{tr(locale,'Recorded research environment','Environnement de recherche enregistré')} ↓</a></p></article></div><section className="section"><h2>{tr(locale,'Artifact registry','Registre des artefacts')}</h2><p>{tr(locale,'Each download records its byte checksum, source commit, version, licence status and evidence status.','Chaque téléchargement indique son empreinte binaire, commit source, version, statut de licence et statut de preuve.')}</p><div className="table-scroll"><table><thead><tr><th>{tr(locale,'Artifact','Artefact')}</th><th>{tr(locale,'Proof status','Statut de preuve')}</th><th>SHA-256</th></tr></thead><tbody>{content.registry.artifacts.map(a=><tr key={a.id}><td><a href={a.url}>{a.path}</a></td><td>{a.proof_status}</td><td><code>{a.sha256}</code></td></tr>)}</tbody></table></div></section><aside className="notice"><p>{tr(locale,'Final scientific release is pending author metadata, reuse licences and an immutable archive DOI. This candidate is not labelled as an archived publication.','La release scientifique finale attend les métadonnées auteurs, les licences et un DOI d’archive immuable. Cette version candidate n’est pas présentée comme une publication archivée.')}</p></aside></>}

function Cite({locale}:{locale:Locale}){return <><p className="lead">{tr(locale,'Cite the research and the exact version you inspected.','Citer la recherche et la version exacte consultée.')}</p><article className="panel"><p>Batako, E., &amp; Ntumba, M. (2026). <em>{content.title}</em>. {tr(locale,'Scientific draft; companion candidate.','Manuscrit scientifique ; compagnon candidat.')}</p><div className="actions"><a className="button" href="/citations/arccraft.bib">BibTeX ↓</a><a className="button" href="/citations/arccraft.ris">RIS ↓</a><a href={`${repo}/blob/main/CITATION.cff`}>CITATION.cff ↗</a></div><dl><dt>DOI</dt><dd>{tr(locale,'Not assigned — final archive pending.','Non attribué — archive finale en attente.')}</dd><dt>ORCID / {tr(locale,'affiliations','affiliations')}</dt><dd>{tr(locale,'To be supplied by the authors.','À compléter par les auteurs.')}</dd><dt>{tr(locale,'Code / paper / figure licence','Licence code / article / figures')}</dt><dd>{tr(locale,'Author decision pending; no open reuse licence is implied.','Décision des auteurs attendue ; aucune licence de réutilisation ouverte n’est implicite.')}</dd></dl></article><h2>{tr(locale,'Cite the external dataset separately','Citer séparément les données externes')}</h2><p>Espinosa, P., Lledó, J., &amp; Atance, D. (2026). <a href="https://doi.org/10.17632/sw4jmdb2sm.1">Motor insurance portfolio, Mendeley Data, v1</a>. CC BY 4.0.</p><Provenance locale={locale}/></>}

export default function Companion({locale,page}:{locale:Locale;page:Page}){
  return <><a className="skip" href="#main">{tr(locale,'Skip to content','Aller au contenu')}</a><header className="masthead"><a className="brand" href={href(locale,'home')}><span className="brand-symbol" aria-hidden="true">A<span>↗</span></span><span>ARCCRAFT<small>RESEARCH COMPANION</small></span></a><div className="header-tools"><span className="status">{tr(locale,'Research candidate','Version candidate')}</span><a lang={locale==='en'?'fr':'en'} href={href(locale==='en'?'fr':'en',page)}>{locale==='en'?'FR':'EN'}</a><Preferences locale={locale}/><a className="repo-link" href={repo}>GitHub ↗</a></div></header><div className="workspace"><aside className="sidebar"><p className="eyebrow">{tr(locale,'EXPLORE THE RESEARCH','EXPLORER LA RECHERCHE')}</p><nav aria-label={tr(locale,'Main navigation','Navigation principale')}>{pages.map((p,i)=><a key={p} href={href(locale,p)} aria-current={page===p?'page':undefined}><span>{i.toString().padStart(2,'0')}</span>{labels[locale][p]}</a>)}</nav><div className="sidebar-note"><span className="dot"/> {tr(locale,'Evidence before inference','La preuve avant l’inférence')}<p>COMMIT <code>{content.manifest.source_commit.slice(0,7)}</code></p></div></aside><main id="main" tabIndex={-1}>{page!=='home'&&<div className="page-title"><p className="eyebrow">ARCCRAFT / {labels[locale][page].toUpperCase()}</p><h1>{labels[locale][page]}</h1></div>}{page==='home'?<Home locale={locale}/>:page==='paper'?<Paper locale={locale}/>:page==='evidence'?<Evidence locale={locale}/>:page==='figures'?<Figures locale={locale}/>:page==='lab'?<><Notice locale={locale}/><Lab locale={locale}/></>:page==='failure-atlas'?<Atlas locale={locale}/>:page==='data'?<Data locale={locale}/>:page==='reproducibility'?<Reproducibility locale={locale}/>:page==='limitations'?<><Notice locale={locale}/><div className="limitations">{limits.map(([en,body,fr,bodyFr])=><article className="claim" key={en}><h2>{tr(locale,en,fr)}</h2><p>{tr(locale,body,bodyFr)}</p></article>)}</div><Provenance locale={locale}/></>:<Cite locale={locale}/>}<footer><span>ARCCRAFT · {tr(locale,'Scientific companion','Compagnon scientifique')}</span><a href={href(locale,'limitations')}>{tr(locale,'Evidence boundaries','Limites de preuve')} ↗</a><span>{tr(locale,'Candidate · archive pending','Candidat · archive en attente')}</span></footer></main></div></>
}
