'use client';
import {Locale,tr,href} from './i18n';
type Scalar=string|number|boolean|null;
export type RunRecord={run_id:string;proof_status:string;mode:string;science_commit:string;output_semantic_sha256:string;historical_fingerprint?:string;duration_seconds?:number;selected_world?:unknown;result:unknown;gates?:Record<string,number>;classes?:Record<string,Record<string,Scalar>>;correlations?:Record<string,number|null>;reverse_stress?:Record<string,Scalar>|null;atlas?:Record<string,unknown>[];parameters:Record<string,Scalar>;warnings?:string[];[key:string]:unknown};
function save(value:unknown,name:string,type='application/json'){const blob=new Blob([typeof value==='string'?value:JSON.stringify(value,null,2)],{type});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
export default function RunResult({run,locale}:{run:RunRecord;locale:Locale}){
 const {result,atlas,...manifest}=run;
 function csv(){if(Array.isArray(result)){const keys=Object.keys(result[0]??{});save([keys.join(','),...result.map(r=>keys.map(k=>JSON.stringify(r[k]??'')).join(','))].join('\n'),`arccraft-${run.run_id}.csv`,'text/csv')}else{const rows:Record<string,unknown>[]=[];function flatten(value:unknown,path=''){if(value&&typeof value==='object'){for(const [key,v]of Object.entries(value))flatten(v,path?`${path}.${key}`:key)}else rows.push({metric_id:path,value:value??null})}flatten(result);save('metric_id,value\n'+rows.map(r=>`${JSON.stringify(r.metric_id)},${JSON.stringify(r.value??'')}`).join('\n'),`arccraft-${run.run_id}.csv`,'text/csv')}save(manifest,`arccraft-${run.run_id}.manifest.json`)}
 function openAtlas(){try{sessionStorage.setItem('arccraft-live-atlas-v1',JSON.stringify({provenance:manifest,rows:atlas?.map(r=>({...r,run_id:run.run_id}))}));window.location.href=href(locale,'failure-atlas')+'?source=live'}catch{alert(tr(locale,'Browser storage unavailable. Download the complete run instead.','Stockage navigateur indisponible. Télécharger le run complet.'))}}
 const motor=result as {predicted_claim_count?:Record<string,number>;predicted_incurred?:Record<string,number>;predicted_loss_ratio?:Record<string,number>;validation?:Record<string,number|boolean>};
 return <article className="run-result"><p className="eyebrow">LIVE / {run.mode}</p><h2>{run.proof_status}</h2><dl className="run-meta"><dt>Run</dt><dd><code>{run.run_id}</code></dd><dt>{tr(locale,'Scientific commit','Commit scientifique')}</dt><dd><code>{run.science_commit}</code></dd><dt>SHA-256</dt><dd><code>{run.output_semantic_sha256}</code></dd><dt>{tr(locale,'Runtime / duration','Environnement / durée')}</dt><dd>{JSON.stringify(run.runtime)} · {run.duration_seconds?.toFixed(3)} s</dd></dl>
 {run.warnings&&<aside className="notice"><div>{run.warnings.map(w=><p key={w}>{w}</p>)}</div></aside>}
 {run.classes&&<><h3>{tr(locale,'Executed scenario classes','Classes de scénario exécutées')}</h3><div className="table-scroll"><table><caption>{tr(locale,'Accepted worlds; synthetic failure rate and mean combined ratio. Exploratory class reported separately.','Mondes acceptés ; taux d’échec synthétique et ratio combiné moyen. Classe exploratoire rapportée séparément.')}</caption><thead><tr><th>{tr(locale,'Class','Classe')}</th><th>{tr(locale,'Accepted','Acceptés')}</th><th>{tr(locale,'Failure rate','Taux d’échec')}</th><th>{tr(locale,'Mean ratio','Ratio moyen')}</th></tr></thead><tbody>{Object.entries(run.classes).map(([name,c])=><tr key={name}><td>{name}</td><td>{c.mondes_acceptes}</td><td>{(Number(c.taux_echec_synthetique)*100).toFixed(3)} %</td><td>{Number(c.ratio_combine_moyen).toFixed(6)}</td></tr>)}</tbody></table></div></>}
 {run.gates&&<><h3>{tr(locale,'Failure gates','Seuils d’échec')}</h3><dl>{Object.entries(run.gates).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl></>}
 {motor.predicted_claim_count&&<><h3>{tr(locale,'Motor projection','Projection automobile')}</h3><div className="table-scroll"><table><thead><tr><th>{tr(locale,'Metric','Métrique')}</th><th>{tr(locale,'Mean','Moyenne')}</th><th>q025</th><th>q975</th></tr></thead><tbody>{[['Claim count',motor.predicted_claim_count],['Incurred · source currency',motor.predicted_incurred],['Loss ratio',motor.predicted_loss_ratio]].map(([name,v])=>{const values=v as Record<string,number>;return <tr key={name as string}><td>{name as string}</td>{['mean','q025','q975'].map(k=><td key={k}>{values[k].toLocaleString(locale,{maximumFractionDigits:6})}</td>)}</tr>})}</tbody></table></div><details open><summary>{tr(locale,'Retrospective validation','Validation rétrospective')}</summary><pre>{JSON.stringify(motor.validation,null,2)}</pre></details></>}
 {run.correlations&&<details><summary>{tr(locale,'Rank correlations — association only','Corrélations de rang — association uniquement')}</summary><pre>{JSON.stringify(run.correlations,null,2)}</pre></details>}{run.reverse_stress&&<details><summary>{tr(locale,'Reverse stress — nearest found, not a global optimum','Stress inverse — plus proche trouvé, pas un optimum global')}</summary><pre>{JSON.stringify(run.reverse_stress,null,2)}</pre></details>}
 <div className="actions"><button className="button" onClick={()=>save(run,`arccraft-${run.run_id}.json`)}>{tr(locale,'Complete run + manifest','Run complet et manifeste')} JSON ↓</button><button className="button" onClick={csv}>CSV + {tr(locale,'manifest','manifeste')} ↓</button>{atlas&&<button className="button" onClick={openAtlas}>{tr(locale,'Inspect this run’s atlas','Inspecter l’Atlas de ce run')} →</button>}</div><details><summary>{tr(locale,'All versions, parameters, streams and checksums','Toutes les versions, paramètres, flux et empreintes')}</summary><pre>{JSON.stringify(manifest,null,2)}</pre></details></article>
}
